version: '3.8'
services:
  task-service:
    container_name: task-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8080'  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus:rw
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
    driver: local